### PR TITLE
Ticket/aotech 6694 data validation

### PR DESCRIPTION
**Pull request by jmichaelward**

### CODE REVIEW

**Comment by phatsk** [comment]
Overall the additions on the CLI are slick! A couple notes:

- Let's move away from emoji on the CLI - I like the style, but it breaks WP-CLI tables (at least for me). We should probably stick to colorized characters. "X" obviously for failed verifications, not sure what (if anything) for passes.
- I was looking at postmeta fails, and there's a couple of things to investigate
- [ ] Source site data may have null values that may not be making it during sync, we need to check this.
- [ ] It looks like at least the `_encloseme` metavalue is being duplicated somewhere along the line - the values on both sites are the same but having two values on the destination site is causing a fail.

**Comment by jmichaelward** [comment]
@phatsk I have seen instances where the source site had an _encloseme meta value, but the destination site did not. Is that something produced by Press Sync?

In terms of emoji, I'm fine with moving away from them. Not sure why it's breaking tables for you. I'm pretty sure there's a standard ASCII checkmark we can use.

**Comment by jmichaelward** [comment]
Ooops...didn't mean to close the PR. Silly GitHub.

**Comment by phatsk** [comment]
@jmichaelward the `_encloseme` meta attribute is added by WordPress via the `_publish_post_hook` method which appears to be hooked to `publish_post` in `wp-includes/default-filters.php`. WP uses `add_post_meta`, which notes:

>Note that if the given key already exists among custom fields of the specified post, another custom field with the same key is added unless the $unique argument is set to true, in which case, no changes are made.

Given that, I'm not sure why we're getting the duplicate on sync since:

```
add_post_meta( $post_id, '_encloseme', '1' );
```

suggests that `$unique` is indeed true.

**Comment by phatsk** [comment]
@jmichaelward ah-ha! According to https://wordpress.stackexchange.com/a/20929/20143

> _encloseme is added to a post when it's published. The wp-cron process should get scheduled shortly thereafter to process the post to look for enclosures.
> In other words, it cleans them up normally later. Nothing to worry about.

My takeaway is that we can safely ignore the `_encloseme` field when doing comparisons. I wonder if there are other built-in WP fields that we should ignore?

**Pull request closed without merging**
